CREATE TABLE IF NOT EXISTS COUNTRY
(
    ID INTEGER AUTO_INCREMENT
    PRIMARY KEY,
    COUNTRY_NAME VARCHAR(255)
    );
CREATE TABLE IF NOT EXISTS AIRPORT
(
    ID INTEGER AUTO_INCREMENT
        PRIMARY KEY,
    AIRPORT_NAME VARCHAR(255),
    COUNTRY_ID INTEGER NOT NULL,
    CONSTRAINT FKCOUNTRYID
        FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS PLANE
(
    ID INTEGER AUTO_INCREMENT
    PRIMARY KEY,
    COUNT_OF_SEATS INTEGER NOT NULL,
    TYPE_OF_AIRCRAFT VARCHAR(255)
    );
CREATE TABLE IF NOT EXISTS PASSENGER
(
    ID INTEGER AUTO_INCREMENT
    PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    PASSPORT VARCHAR(11),
    PHONE_NUMBER VARCHAR(255) NOT NULL
    );
CREATE TABLE IF NOT EXISTS PILOT
(
    ID INTEGER AUTO_INCREMENT
    PRIMARY KEY,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255)
    );
CREATE TABLE IF NOT EXISTS FLIGHT
(
    ID INTEGER AUTO_INCREMENT
        PRIMARY KEY,
    DEPARTURE_TIME TIMESTAMP NOT NULL,
    DESTINATION_TIME TIMESTAMP NOT NULL,
    NUMBER VARCHAR(255),
    DEPARTURE_ID INTEGER NOT NULL,
    DESTINATION_ID INTEGER NOT NULL,
    PLANE_ID INTEGER NOT NULL,
    CONSTRAINT FKPLANEID
        FOREIGN KEY (PLANE_ID) REFERENCES PLANE (ID),
    CONSTRAINT FKDEPARTUREID
        FOREIGN KEY (DEPARTURE_ID) REFERENCES COUNTRY (ID),
    CONSTRAINT FKDESTINATIONID
        FOREIGN KEY (DESTINATION_ID) REFERENCES COUNTRY (ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS TICKET
(
    ID INTEGER AUTO_INCREMENT
    PRIMARY KEY,
    NUMBER VARCHAR(255),
    PRICE INTEGER NOT NULL,
    PASSENGER_ID INTEGER NOT NULL,
    CONSTRAINT FKPASSENGERID
    FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER (ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
    );
CREATE TABLE IF NOT EXISTS FLIGHT_TICKETS
(
    FLIGHTS_ID INTEGER NOT NULL,
    TICKETS_ID INTEGER NOT NULL,
    CONSTRAINT FKFLIGHTSID
        FOREIGN KEY (FLIGHTS_ID) REFERENCES FLIGHT (ID),
    CONSTRAINT FKTICKETSID
        FOREIGN KEY (TICKETS_ID) REFERENCES TICKET (ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PILOT_FLIGHTS
(
    PILOTS_ID INTEGER NOT NULL,
    FLIGHTS_ID INTEGER NOT NULL,
    CONSTRAINT FKFLIGHTS_PILOTID
        FOREIGN KEY (FLIGHTS_ID) REFERENCES FLIGHT (ID),
    CONSTRAINT FKPILOTID
        FOREIGN KEY  (PILOTS_ID) REFERENCES PILOT (ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS TICKET_PRICE
(
    ID INTEGER AUTO_INCREMENT
        PRIMARY KEY,
    PRICE DECIMAL(19,2) NOT NULL,
    TYPE_OF_CLASS VARCHAR(255),
    FLIGHT_ID INTEGER NOT NULL,
    CONSTRAINT FKFLIGHTID
        FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHT (ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);