INSERT INTO PUBLIC.COUNTRY (COUNTRY_NAME) VALUES ('Czech Republic');
INSERT INTO PUBLIC.COUNTRY (COUNTRY_NAME) VALUES ('Hungary');
INSERT INTO PUBLIC.COUNTRY (COUNTRY_NAME) VALUES ('Chile');
INSERT INTO PUBLIC.COUNTRY (COUNTRY_NAME) VALUES ('Greece');

INSERT INTO PUBLIC.AIRPORT (AIRPORT_NAME, COUNTRY_ID) VALUES ('Pardubice', 1);
INSERT INTO PUBLIC.AIRPORT (AIRPORT_NAME, COUNTRY_ID) VALUES ('Pech-Filth', 2);
INSERT INTO PUBLIC.AIRPORT (AIRPORT_NAME, COUNTRY_ID) VALUES ('Arturo Merino Benitez', 3);
INSERT INTO PUBLIC.AIRPORT (AIRPORT_NAME, COUNTRY_ID) VALUES ('Eliftherios Venizelos', 4);

INSERT INTO PUBLIC.PLANE (TYPE_OF_AIRCRAFT, COUNT_OF_SEATS) VALUES ('Sukhoi SuperJet-100', 98);
INSERT INTO PUBLIC.PLANE (TYPE_OF_AIRCRAFT, COUNT_OF_SEATS) VALUES ('TY-134', 80);
INSERT INTO PUBLIC.PLANE (TYPE_OF_AIRCRAFT, COUNT_OF_SEATS) VALUES ('Airbus A310', 183);
INSERT INTO PUBLIC.PLANE (TYPE_OF_AIRCRAFT, COUNT_OF_SEATS) VALUES ('Boeing-737', 117);

INSERT INTO PUBLIC.PASSENGER (EMAIL, FIRST_NAME, LAST_NAME, PASSPORT, PHONE_NUMBER) VALUES ('alex@mail.ru', 'A', 'Matveev', '1120 444123' ,'+79212312211');
INSERT INTO PUBLIC.PASSENGER (EMAIL, FIRST_NAME, LAST_NAME, PASSPORT, PHONE_NUMBER) VALUES ('smirnov@yandex.ru', 'Alexandr', 'Smirnov', '1230 890654' ,'+79113334422');
INSERT INTO PUBLIC.PASSENGER (EMAIL, FIRST_NAME, LAST_NAME, PASSPORT, PHONE_NUMBER) VALUES ('sm@gmail.com', 'James', 'Smith', 'AB 234563' ,'+445316689');
INSERT INTO PUBLIC.PASSENGER (EMAIL, FIRST_NAME, LAST_NAME, PASSPORT, PHONE_NUMBER) VALUES ('lev@mail.ru', 'Lev', 'Bublikov', '3241 675432' ,'+79094567321');

INSERT INTO PUBLIC.PILOT (FIRST_NAME, LAST_NAME) VALUES ('Ivan', 'Sidorov');
INSERT INTO PUBLIC.PILOT (FIRST_NAME, LAST_NAME) VALUES ('Kirill', 'Petrov');
INSERT INTO PUBLIC.PILOT (FIRST_NAME, LAST_NAME) VALUES ('Matias', 'Milani');
INSERT INTO PUBLIC.PILOT (FIRST_NAME, LAST_NAME) VALUES ('James', 'Smith');

INSERT INTO PUBLIC.FLIGHT (NUMBER, PLANE_ID, DEPARTURE_ID, DESTINATION_ID, DEPARTURE_TIME, DESTINATION_TIME)
VALUES ('1234', 1, 2, 1, '2021-09-01 11:22:00', '2021-09-01 14:50:00');
INSERT INTO PUBLIC.FLIGHT (NUMBER, PLANE_ID, DEPARTURE_ID, DESTINATION_ID, DEPARTURE_TIME, DESTINATION_TIME)
VALUES ('1274', 2, 1, 2, '2021-09-02 19:00:00', '2021-09-02 21:30:00');
INSERT INTO PUBLIC.FLIGHT (NUMBER, PLANE_ID, DEPARTURE_ID, DESTINATION_ID, DEPARTURE_TIME, DESTINATION_TIME)
VALUES ('1134', 3, 3, 3, '2021-09-03 04:02:00', '2021-09-03 15:20:00');
INSERT INTO PUBLIC.FLIGHT (NUMBER, PLANE_ID, DEPARTURE_ID, DESTINATION_ID, DEPARTURE_TIME, DESTINATION_TIME)
VALUES ('1934', 4, 4, 4, '2021-09-04 08:13:00', '2021-09-04 11:00:00');

INSERT INTO PUBLIC.TICKET (PRICE, PASSENGER_ID) VALUES (3789, 1);
INSERT INTO PUBLIC.TICKET (PRICE, PASSENGER_ID) VALUES (18389, 2);
INSERT INTO PUBLIC.TICKET (PRICE, PASSENGER_ID) VALUES (6789, 3);
INSERT INTO PUBLIC.TICKET (PRICE, PASSENGER_ID) VALUES (10459, 4);

INSERT INTO PUBLIC.TICKET_PRICE (PRICE, TYPE_OF_CLASS, FLIGHT_ID) VALUES (13589.60, 'Economy', 1);
INSERT INTO PUBLIC.TICKET_PRICE (PRICE, TYPE_OF_CLASS, FLIGHT_ID) VALUES (10244.20, 'Economy', 2);
INSERT INTO PUBLIC.TICKET_PRICE (PRICE, TYPE_OF_CLASS, FLIGHT_ID) VALUES (84576.30, 'Business', 3);
INSERT INTO PUBLIC.TICKET_PRICE (PRICE, TYPE_OF_CLASS, FLIGHT_ID) VALUES (3467.00, 'Economy', 4);